##################################################
### CREATE DRIVER - Budi Santoso
##################################################
POST http://localhost:3001/api/drivers
Content-Type: application/json

{
  "name": "dimas test"
}

##################################################
### CREATE VEHICLE - Truck B 1234 ABC
##################################################
POST http://localhost:3001/api/vehicles
Content-Type: application/json

{
  "plate": "D 1 MAS",
  "type": "MERCY"
}

##################################################
### CREATE WAREHOUSE - Gudang Jakarta
##################################################
POST http://localhost:3001/api/warehouses
Content-Type: application/json

{
  "name": "Gudang Jakarta 2 ",
  "city": "Jakarta",
  "latitude": -6.208763,
  "longitude": 106.845599
}

##################################################
### CREATE WAREHOUSE - Gudang Bandung
##################################################
POST http://localhost:3001/api/warehouses
Content-Type: application/json

{
  "name": "Gudang Bandung 2",
  "city": "Bandung",
  "latitude": -6.914744,
  "longitude": 107.609810
}

##################################################
### CREATE ASSIGNMENT - Jakarta to Bandung
##################################################
POST http://localhost:3001/api/assignments
Content-Type: application/json

{
  "driverId": 8,
  "vehicleId": 6,
  "originId": 4,
  "destinationId": 5
}

##################################################
### START TRIP - Driver Tap In
##################################################
POST http://localhost:3001/api/trips/start
Content-Type: application/json

{
  "assignmentId": 11
}

##################################################
### PUSH GPS - Position 1
##################################################
POST http://localhost:3001/api/gps/push
Content-Type: application/json

{
  "tripId": 6,
  "vehicleId": 6,
  "latitude": -6.300000,
  "longitude": 107.000000,
  "speed": 60
}

##################################################
### PUSH GPS - Position 2
##################################################
POST http://localhost:3001/api/gps/push
Content-Type: application/json

{
  "tripId": 6,
  "vehicleId": 6,
  "latitude": -6.500000,
  "longitude": 107.300000,
  "speed": 55
}

##################################################
### END TRIP - Driver B to Gudang A
##################################################
POST http://localhost:3001/api/trips/end
Content-Type: application/json

{
  "tripId": 6,
  "destinationId": 5,
  "avgSpeed": 52
}

##################################################
### DASHBOARD MAP - ACTIVE VEHICLES
##################################################
GET http://localhost:3001/api/dashboard/map
